baseurl: 'https://services.m3o.com'
languageCode: 'en-us'
title: 'Micro Services'
themesDir: '../..'
theme: 'hugo-tania'
summaryLength: 10

source: "https://github.com/micro/services"

params:
  titleEmoji: ''
  socialOptions:
    github:
    twitter:

menu:
  header:
    - name: Explore
      url: '/explore/'
  footer:
    - name: 'Â© 2020 Micro Services, Inc.'
      url: 'https://m3o.com'

markup:
  highlight:
    noClasses: false
    lineNos: true
  goldmark:
    renderer:
      unsafe: true

permalinks:
  post: /:filename
